<?php
$chistes=[
  "¡Hola! ¿Está Agustín? — No, estoy incomodín.",
  "¿Qué hace una abeja en un gimnasio? — ¡Zum-ba!",
  "Primer acto: Un tomate. Segundo acto: Un tomate. Tercer acto: Un tomate. ¿Cómo se llama la obra? — Tomate tres.",
  "¡Camarero, ese bistec tiene muchos nervios! — Es normal, es la primera vez que se lo comen.",
  "¿Cuál es el último animal que subió al Arca de Noé? — El del-fín.",
  "¿Qué le dice un pez a otro? — ¡Nada!",
  "¡Ayer vendí mi coche por una ganga! —¿Y cuál era la ganga? — ¡Un Opel Corsa!",
  "¿Qué dice un jardinero cuando se pone celoso? — ¡La envidia me corroe!",
  "¿Qué hace un perro con un taladro? — Taladrando.",
  "¡Me da un café con leche, por favor! —¿Se lo pongo en vaso o en taza? — En taza, pero con 'Z'.",
  "¿Qué hace una persona con dos orejas en una mano? — Escuchando.",
  "¿Cuál es el colmo de un panadero? — Que se le acabe el pan.",
  "¿Por qué los pájaros no usan Facebook? — Porque ya tienen Twitter.",
  "¿Qué le dice un semáforo a otro? — No me mires que me pongo colorado.",
  "¡Van dos y se cae el del medio!",
  "¿Cuál es el animal más tonto del mundo? — El oso polar, porque vive en el hielo y no sabe que existe el agua caliente.",
  "¿Qué le dice una pared a otra? — Nos vemos en la esquina.",
  "¿Por qué los elefantes no usan ordenador? — Porque le tienen miedo al mouse.",
  "¿Sabes qué le dice un pez a su hijo? — ¡Concéntrate, que ya estoy a punto de explotar! (Chiste de pez globo)",
  "¿Qué hace un mudo bailando? — Discoteca.",
  "¿Qué le dice un cable a otro? — Somos los enchufados.",
  "¿Qué le dice un cero a un ocho? — ¡Qué cinturón tan chulo!",
  "¿Qué es un átomo? — Un átomo es un átomo que no se toma.",
  "¿Qué hace un perro en la sombra? — Un perro con sombra.",
  "¿Cuál es el café más peligroso del mundo? — El ex-presso.",
  "¿Qué le dice un duende a otro? — ¡Duende aquí, duende allá!",
  "¿Por qué un espejo está triste? — Porque siempre le refleja su soledad.",
  "¿Qué hace una persona con dos narices? — Estornudar dos veces.",
  "¿Cuál es el coche más pequeño del mundo? — El auto móvil.",
  "¿Qué le dice una bombilla a otra? — ¡Eres genial!",
  "¿Qué le dice una pulga a otra? — ¿Andamos o esperamos al perro?",
  "¿Cuál es el colmo de un electricista? — Que su mujer se llame Luz y sus hijos le den calambres.",
  "¿Qué le dice un ojo a otro? — Estamos conectados.",
  "¿Qué es un gusano? — Un bicho malhumorado porque no se le considera la mitad de otro animal.",
  "¿Cuál es la fruta más paciente? — La pera.",
  "¿Qué le dice un billete de 50€ a uno de 10€? — ¡Somos los billetes ricos!",
  "¿Qué le dice un espagueti a otro? — ¿Qué pasa, spaguetti?",
  "¿Qué hace un policía en una nevera? — ¡Polo frío!",
  "¿Qué le dice un espía a otro? — Somos agentes secretos.",
  "¿Por qué una silla está tan orgullosa? — Porque es una silla de alto nivel.",
  "¿Qué le dice un camello a otro? — ¡Tenemos joroba de ser camellos!",
  "¿Qué le dice un número a otro? — Somos hermanos.",
  "¿Qué hace un perro en una panadería? — ¡Perro caliente!",
  "¿Qué le dice un mosquito a un humano? — ¡No me pises, te pido por favor!",
  "¿Qué hace un fantasma en un ascensor? — Subir y bajar.",
  "¿Qué le dice un semáforo a un coche? — ¡Pasa, que te dejo!",
  "¿Cuál es la tarta más peligrosa? — La tarta-leta.",
  "¿Qué hace un pez en el mar? — Nadar como un pez.",
  "¿Qué le dice un lápiz a otro? — Eres un punto aparte.",
  "¿Qué le dice un jardinero a otro? — ¡A regar se ha dicho!"
];

echo $chistes[random_int(0,count($chistes)-1)];
?>